### ISSUE TITLE
Command line for the strain and stress tensor

### ISSUE THREAD

**Issue by ATAKOURA** [thelfer/MFrontGenericInterfaceSupport#55]
I come back to you to get the command line I need in the attached code
 https://thelfer.github.io/mgis/web/mgis_fenics.html: on Phase-field approach
the fracture  to extract the deformation and stress tensor associated with the displacement field. The goal is to visualize it with Paraview.

**Comment by bleyerj** [comment]
You can check this demo https://thelfer.github.io/mgis/web/mgis_fenics_small_strain_elastoplasticity.html where we get a state variable by projecting it on a suitable function space. You can do the same with the stress field using for instance:
`problem_u.get_flux("Stress", project_on=("DG",0))`
If you want to access the strain you can for instance declare it as a state variable in MFront and do `problem_u.get_state_variable("Strain", project_on=('DG", 0))`

**Comment by thelfer** [comment]
Hi @bleyerj,
Thanks for the answer.
Storing the strain in a state variable is just a bit two much since we keep the gradients in `mgis` `MaterialDataManager` (hence we would duplicate memory, which is bad), isn't it ?
Would it be better to have a `get_gradient` method similar to the `get_flux` (I can try to implement it) ?
Best,
Thomas

**Comment by bleyerj** [comment]
@thelfer OK with that, should be very similar to `get_flux` indeed

**Comment by thelfer** [comment]
Hi,

Just had a look at it. It looks like @bleyerj have already done all the work, so the `get_gradient` seems a simple copy/paste version of the `get_flux` method (see below). Unfortunatly, my virtual machine on which I installed fenics seems now broken (I just upgraded VirtualBox...). It will take me some time to reinstall it.

@ATAKOURA would test this code (just copy/paste in the the file `nonlinear_problem.py` near the `get_flux` method in your installation directory and tell us if it works. Thanks.

Thomas

~~~~{.python}
    def get_gradient(self, name, project_on=None):
        """
        Returns the function associated with a gradient

        Parameters
        ----------
        name : str
            Name of the gradient
        project_on : {None, (space, degree)}
            Either None or a tuple (space, degree) such as ("CG", 1), ("DG", 0), etc.

        Returns
        -------
        `dolfin.Function`
            A function defined on the corresponding Quadrature function space if project_on=None (default).
            Otherwise a classical function belonging to the FunctionSpace (space, degree)

        """
        if project_on is None:
            return self.gradients[name].function
        else:
            return self.gradients[name].project_on(*project_on)
~~~~

**Comment by thelfer** [comment]
@bleyerj My solution don't work:

~~~~
Traceback (most recent call last):
  File "mgis_fenics_small_strain_elastoplasticity.py", line 176, in <module>
    e0 = problem.get_gradient("Strain", project_on=("DG", 0))
  File "/home/tom/codes/mgis/master/install-56ae53ea/lib/python3.8/site-packages/mgis/fenics/nonlinear_problem.py", line 437, in get_gradient
    return self.gradients[name].project_on(*project_on)
AttributeError: 'Gradient' object has no attribute 'project_on'
~~~~

because de `Gradient` class does not inherit from `QuadratureFunction`as does the `Flux`class. @bleyerj Is this something that we can change ?

**Comment by thelfer** [comment]
@bleyerj Here is a quick fix that seems to work. However, many things are duplicated in `Gradient` and `QuadratureFunction`. Would you have a look at it ?
[fenics.zip](https://github.com/thelfer/MFrontGenericInterfaceSupport/files/5538745/fenics.zip)

**Comment by thelfer** [comment]
@bleyerj I can confirm that the strains can be  correctly exported with this fix.

**Comment by bleyerj** [comment]
Thanks I have refactored a bit the QuadratureFunction part in #57
